"""empty message

Revision ID: 4c2aa67bfbc6
Revises: 
Create Date: 2025-03-25 18:19:00.385561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2aa67bfbc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('professional_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('professional_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
